#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# set this to your active development branch
development_branch="development"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

# only check commit messages on main development branch
[ "$current_branch" != "$development_branch" ] && exit 0

# regex to validate the commit msg
commit_regex='(SVM-[0-9]+|merge)'
error_msg="Aborting commit. Your commit message is missing either a JIRA Issue ('SVM-1111') or 'Merge'"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
```
